# --- App1 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test123
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test123
  template:
    metadata:
      labels:
        app: test123
    spec:
      containers:
        - name: app1
          image: nginx:latest            # 🔁 change to your image for app1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test123-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: test123
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
