# --- App2 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: httpd:latest           # 🔁 change to your image for app2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
